// <auto-generated />
namespace LMSFinance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class submitform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(submitform));
        
        string IMigrationMetadata.Id
        {
            get { return "202211150413171_submitform"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
